export { default as BuiltWithNuxtDark } from '../../node_modules/@docus/theme/dist/components/atoms/icons/BuiltWithNuxtDark.vue'
export { default as BuiltWithNuxtLight } from '../../node_modules/@docus/theme/dist/components/atoms/icons/BuiltWithNuxtLight.vue'
export { default as IconAlgolia } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconAlgolia.vue'
export { default as IconArrowLeft } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconArrowLeft.vue'
export { default as IconArrowRight } from '../../components/atoms/icons/IconArrowRight.vue'
export { default as IconBadgeCheck } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconBadgeCheck.vue'
export { default as IconCheck } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconCheck.vue'
export { default as IconCheckCircle } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconCheckCircle.vue'
export { default as IconChevronRight } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconChevronRight.vue'
export { default as IconClipboardCheck } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconClipboardCheck.vue'
export { default as IconClipboardCopy } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconClipboardCopy.vue'
export { default as IconCodeSandbox } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconCodeSandbox.vue'
export { default as IconCopy } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconCopy.vue'
export { default as IconEdit } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconEdit.vue'
export { default as IconExclamationCircle } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconExclamationCircle.vue'
export { default as IconExternalLink } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconExternalLink.vue'
export { default as IconGitHub } from '../../components/atoms/icons/IconGitHub.vue'
export { default as IconHeart } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconHeart.vue'
export { default as IconInformationCircle } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconInformationCircle.vue'
export { default as IconMenu } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconMenu.vue'
export { default as IconMenuAlt } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconMenuAlt.vue'
export { default as IconMoon } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconMoon.vue'
export { default as IconNuxt } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconNuxt.vue'
export { default as IconNuxtContent } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconNuxtContent.vue'
export { default as IconNuxtLabs } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconNuxtLabs.vue'
export { default as IconSearch } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconSearch.vue'
export { default as IconSun } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconSun.vue'
export { default as IconTranslate } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconTranslate.vue'
export { default as IconTwitter } from '../../components/atoms/icons/IconTwitter.vue'
export { default as IconVite } from '../../components/atoms/icons/IconVite.vue'
export { default as IconVue } from '../../components/atoms/icons/IconVue.vue'
export { default as IconWindi } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconWindi.vue'
export { default as IconX } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconX.vue'
export { default as IconXCircle } from '../../node_modules/@docus/theme/dist/components/atoms/icons/IconXCircle.vue'
export { default as ProseA } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseA.vue'
export { default as ProseBlockquote } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseBlockquote.vue'
export { default as ProseCode } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseCode.vue'
export { default as ProseCodeInline } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseCodeInline.vue'
export { default as ProseEm } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseEm.vue'
export { default as ProseH1 } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseH1.vue'
export { default as ProseH2 } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseH2.vue'
export { default as ProseH3 } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseH3.vue'
export { default as ProseH4 } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseH4.vue'
export { default as ProseHr } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseHr.vue'
export { default as ProseImg } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseImg.vue'
export { default as ProseLi } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseLi.vue'
export { default as ProseOl } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseOl.vue'
export { default as ProseParagraph } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseParagraph.vue'
export { default as ProseStrong } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseStrong.vue'
export { default as ProseTable } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseTable.vue'
export { default as ProseTbody } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseTbody.vue'
export { default as ProseTd } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseTd.vue'
export { default as ProseTh } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseTh.vue'
export { default as ProseThead } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseThead.vue'
export { default as ProseTr } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseTr.vue'
export { default as ProseUl } from '../../node_modules/@docus/theme/dist/components/atoms/prose/ProseUl.vue'
export { default as AppAside } from '../../components/app/AppAside.vue'
export { default as AppBanner } from '../../node_modules/@docus/theme/dist/components/organisms/app/AppBanner.vue'
export { default as AppFooter } from '../../components/app/AppFooter.vue'
export { default as AppHeader } from '../../components/app/AppHeader.vue'
export { default as AppLayout } from '../../components/app/AppLayout.vue'
export { default as AppPage } from '../../node_modules/@docus/theme/dist/components/organisms/app/AppPage.vue'
export { default as AppTemplate } from '../../node_modules/@docus/theme/dist/components/organisms/app/AppTemplate.vue'
export { default as BlogpostCard } from '../../node_modules/@docus/theme/dist/components/organisms/blog/BlogpostCard.vue'
export { default as BlogpostList } from '../../node_modules/@docus/theme/dist/components/organisms/blog/BlogpostList.vue'
export { default as BlogpostToc } from '../../node_modules/@docus/theme/dist/components/organisms/blog/BlogpostToc.vue'
export { default as AsideBottom } from '../../node_modules/@docus/theme/dist/components/organisms/dev-slots/AsideBottom.vue'
export { default as AsideTop } from '../../node_modules/@docus/theme/dist/components/organisms/dev-slots/AsideTop.vue'
export { default as FooterBody } from '../../node_modules/@docus/theme/dist/components/organisms/dev-slots/FooterBody.vue'
export { default as HeaderNavigation } from '../../node_modules/@docus/theme/dist/components/organisms/dev-slots/HeaderNavigation.vue'
export { default as PageTocBottom } from '../../node_modules/@docus/theme/dist/components/organisms/dev-slots/PageTocBottom.vue'
export { default as PageTocTop } from '../../node_modules/@docus/theme/dist/components/organisms/dev-slots/PageTocTop.vue'
export { default as SlotBase } from '../../node_modules/@docus/theme/dist/components/organisms/dev-slots/SlotBase.vue'
export { default as EditOnGithub } from '../../components/atoms/EditOnGithub.vue'
export { default as PageMobileToc } from '../../node_modules/@docus/theme/dist/components/organisms/page/PageMobileToc.vue'
export { default as PagePrevNext } from '../../node_modules/@docus/theme/dist/components/organisms/page/PagePrevNext.vue'
export { default as PageToc } from '../../node_modules/@docus/theme/dist/components/organisms/page/PageToc.vue'
export { default as PageTocList } from '../../node_modules/@docus/theme/dist/components/organisms/page/PageTocList.vue'
export { default as Page } from '../../node_modules/@docus/app/dist/app/components/Page.vue'
export { default as Alert } from '../../components/atoms/Alert.vue'
export { default as Badge } from '../../node_modules/@docus/theme/dist/components/atoms/Badge.vue'
export { default as ButtonLink } from '../../components/atoms/ButtonLink.vue'
export { default as Card } from '../../node_modules/@docus/theme/dist/components/atoms/Card.vue'
export { default as CodeBlock } from '../../node_modules/@docus/theme/dist/components/atoms/CodeBlock.vue'
export { default as CodeGroup } from '../../node_modules/@docus/theme/dist/components/atoms/CodeGroup.vue'
export { default as ColorSwitcher } from '../../node_modules/@docus/theme/dist/components/atoms/ColorSwitcher.vue'
export { default as CopyButton } from '../../node_modules/@docus/theme/dist/components/atoms/CopyButton.vue'
export { default as Dropdown } from '../../node_modules/@docus/theme/dist/components/atoms/Dropdown.vue'
export { default as HeaderLogo } from '../../node_modules/@docus/theme/dist/components/atoms/HeaderLogo.vue'
export { default as InfoLabel } from '../../node_modules/@docus/theme/dist/components/atoms/InfoLabel.vue'
export { default as InjectComponent } from '../../node_modules/@docus/theme/dist/components/atoms/InjectComponent.vue'
export { default as InjectContent } from '../../node_modules/@docus/theme/dist/components/atoms/InjectContent.vue'
export { default as LangSwitcher } from '../../node_modules/@docus/theme/dist/components/atoms/LangSwitcher.vue'
export { default as Link } from '../../node_modules/@docus/theme/dist/components/atoms/Link.vue'
export { default as List } from '../../node_modules/@docus/theme/dist/components/atoms/List.vue'
export { default as Logo } from '../../components/atoms/Logo.vue'
export { default as Props } from '../../node_modules/@docus/theme/dist/components/atoms/Props.vue'
export { default as ReleaseTag } from '../../node_modules/@docus/theme/dist/components/atoms/ReleaseTag.vue'
export { default as Sandbox } from '../../node_modules/@docus/theme/dist/components/atoms/Sandbox.vue'
export { default as VideoPlayer } from '../../node_modules/@docus/theme/dist/components/atoms/VideoPlayer.vue'
export { default as AlgoliaSearchBox } from '../../components/app/AlgoliaSearchBox.vue'
export { default as AsideNavigation } from '../../components/app/AsideNavigation.vue'
export { default as AsideNavigationItem } from '../../node_modules/@docus/theme/dist/components/molecules/AsideNavigationItem.vue'
export { default as CardGrid } from '../../node_modules/@docus/theme/dist/components/molecules/CardGrid.vue'
export { default as NavigationButton } from '../../node_modules/@docus/theme/dist/components/molecules/NavigationButton.vue'
export { default as PoweredByDocus } from '../../node_modules/@docus/theme/dist/components/molecules/PoweredByDocus.vue'
export { default as SocialIcons } from '../../node_modules/@docus/theme/dist/components/molecules/SocialIcons.vue'
export { default as TabsHeader } from '../../node_modules/@docus/theme/dist/components/molecules/TabsHeader.vue'
export { default as BlockFeatures } from '../../node_modules/@docus/theme/dist/components/organisms/BlockFeatures.vue'
export { default as BlockHero } from '../../node_modules/@docus/theme/dist/components/organisms/BlockHero.vue'
export { default as PageContent } from '../../node_modules/@docus/theme/dist/components/organisms/PageContent.vue'
export { default as PreLaunchHero } from '../../node_modules/@docus/theme/dist/components/organisms/PreLaunchHero.vue'
export { default as PricingBlock } from '../../node_modules/@docus/theme/dist/components/organisms/PricingBlock.vue'
export { default as PricingGrid } from '../../node_modules/@docus/theme/dist/components/organisms/PricingGrid.vue'
export { default as Terminal } from '../../node_modules/@docus/theme/dist/components/organisms/Terminal.vue'
export { default as Blog } from '../../node_modules/@docus/theme/dist/components/templates/Blog.vue'
export { default as BlogPost } from '../../node_modules/@docus/theme/dist/components/templates/BlogPost.vue'
export { default as Docs } from '../../node_modules/@docus/theme/dist/components/templates/Docs.vue'
export { default as Error } from '../../components/templates/Error.vue'
export { default as Marketing } from '../../node_modules/@docus/theme/dist/components/templates/Marketing.vue'
export { default as Releases } from '../../node_modules/@docus/theme/dist/components/templates/Releases.vue'
export { default as DocusContent } from '../../node_modules/@docus/core/dist/runtime/components/DocusContent.vue'
export { default as Markdown } from '../../node_modules/@docus/core/dist/runtime/components/Markdown.vue'
export { default as IconCAPI } from '../../components/atoms/icons/IconCAPI.vue'
export { default as IconCLI } from '../../components/atoms/icons/IconCLI.vue'
export { default as IconClose } from '../../components/atoms/icons/IconClose.vue'
export { default as IconCode } from '../../components/atoms/icons/IconCode.vue'
export { default as IconDevtools } from '../../components/atoms/icons/IconDevtools.vue'
export { default as IconDirectory } from '../../components/atoms/icons/IconDirectory.vue'
export { default as IconFeather } from '../../components/atoms/icons/IconFeather.vue'
export { default as IconFile } from '../../components/atoms/icons/IconFile.vue'
export { default as IconFileSettings } from '../../components/atoms/icons/IconFileSettings.vue'
export { default as IconGit } from '../../components/atoms/icons/IconGit.vue'
export { default as IconHybrid } from '../../components/atoms/icons/IconHybrid.vue'
export { default as IconKit } from '../../components/atoms/icons/IconKit.vue'
export { default as IconNpm } from '../../components/atoms/icons/IconNpm.vue'
export { default as IconNuxtBridge } from '../../components/atoms/icons/IconNuxtBridge.vue'
export { default as IconNuxtNitro } from '../../components/atoms/icons/IconNuxtNitro.vue'
export { default as IconPresets } from '../../components/atoms/icons/IconPresets.vue'
export { default as IconRabbit } from '../../components/atoms/icons/IconRabbit.vue'
export { default as IconSuspense } from '../../components/atoms/icons/IconSuspense.vue'
export { default as IconTypeScript } from '../../components/atoms/icons/IconTypeScript.vue'
export { default as IconWebpack } from '../../components/atoms/icons/IconWebpack.vue'
export { default as LogoAzure } from '../../components/atoms/logo/LogoAzure.vue'
export { default as LogoCloudFlare } from '../../components/atoms/logo/LogoCloudFlare.vue'
export { default as LogoFirebase } from '../../components/atoms/logo/LogoFirebase.vue'
export { default as LogoNetlify } from '../../components/atoms/logo/LogoNetlify.vue'
export { default as LogoPM2 } from '../../components/atoms/logo/LogoPM2.vue'
export { default as LogoVercel } from '../../components/atoms/logo/LogoVercel.vue'
export { default as AsideHeaderNavigation } from '../../components/app/AsideHeaderNavigation.vue'
export { default as Gem } from '../../components/atoms/Gem.vue'
export { default as GitHubButton } from '../../components/atoms/GitHubButton.vue'
export { default as Headline } from '../../components/atoms/Headline.vue'
export { default as NuxtContainer } from '../../components/atoms/NuxtContainer.vue'
export { default as SectionButton } from '../../components/atoms/SectionButton.vue'
export { default as Star } from '../../components/atoms/Star.vue'
export { default as TwitterButton } from '../../components/atoms/TwitterButton.vue'
export { default as HeroParallax } from '../../components/molecules/HeroParallax.vue'
export { default as HeroSection } from '../../components/molecules/HeroSection.vue'
export { default as HomeHero } from '../../components/molecules/HomeHero.vue'
export { default as HomeFeatures } from '../../components/organisms/HomeFeatures.vue'
export { default as SectionContentItem } from '../../components/organisms/SectionContentItem.vue'
export { default as Blank } from '../../components/templates/Blank.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
